export const cryptocurrencies = [
  { id: 'bitcoin', symbol: 'BTC', name: 'Bitcoin' },
  { id: 'ethereum', symbol: 'ETH', name: 'Ethereum' },
  { id: 'binancecoin', symbol: 'BNB', name: 'Binance Coin' },
  { id: 'ripple', symbol: 'XRP', name: 'Ripple' },
  { id: 'cardano', symbol: 'ADA', name: 'Cardano' },
  { id: 'solana', symbol: 'SOL', name: 'Solana' },
  { id: 'polkadot', symbol: 'DOT', name: 'Polkadot' },
  { id: 'dogecoin', symbol: 'DOGE', name: 'Dogecoin' },
  { id: 'avalanche-2', symbol: 'AVAX', name: 'Avalanche' },
  { id: 'matic-network', symbol: 'MATIC', name: 'Polygon' },
  { id: 'chainlink', symbol: 'LINK', name: 'Chainlink' },
  { id: 'uniswap', symbol: 'UNI', name: 'Uniswap' },
  { id: 'litecoin', symbol: 'LTC', name: 'Litecoin' },
  { id: 'tether', symbol: 'USDT', name: 'Tether' },
  { id: 'usd-coin', symbol: 'USDC', name: 'USD Coin' },
  { id: 'dai', symbol: 'DAI', name: 'Dai' },
  { id: 'bitcoin-cash', symbol: 'BCH', name: 'Bitcoin Cash' },
  { id: 'monero', symbol: 'XMR', name: 'Monero' },
  { id: 'stellar', symbol: 'XLM', name: 'Stellar' },
  { id: 'cosmos', symbol: 'ATOM', name: 'Cosmos' },
  { id: 'filecoin', symbol: 'FIL', name: 'Filecoin' },
  { id: 'tezos', symbol: 'XTZ', name: 'Tezos' },
  { id: 'eos', symbol: 'EOS', name: 'EOS' },
  { id: 'aave', symbol: 'AAVE', name: 'Aave' },
  { id: 'algorand', symbol: 'ALGO', name: 'Algorand' },
  { id: 'decentraland', symbol: 'MANA', name: 'Decentraland' },
  { id: 'the-sandbox', symbol: 'SAND', name: 'The Sandbox' },
  { id: 'axie-infinity', symbol: 'AXS', name: 'Axie Infinity' },
  { id: 'curve-dao-token', symbol: 'CRV', name: 'Curve DAO Token' },
  { id: 'compound-governance-token', symbol: 'COMP', name: 'Compound' },
  { id: 'maker', symbol: 'MKR', name: 'Maker' },
  { id: 'yearn-finance', symbol: 'YFI', name: 'Yearn Finance' },
  { id: 'sushi', symbol: 'SUSHI', name: 'SushiSwap' },
  { id: '1inch', symbol: '1INCH', name: '1inch' },
  { id: 'thorchain', symbol: 'RUNE', name: 'THORChain' },
  { id: 'terra-luna', symbol: 'LUNA', name: 'Terra' },
  { id: 'near', symbol: 'NEAR', name: 'NEAR Protocol' },
  { id: 'fantom', symbol: 'FTM', name: 'Fantom' },
  { id: 'harmony', symbol: 'ONE', name: 'Harmony' },
  { id: 'kusama', symbol: 'KSM', name: 'Kusama' },
  { id: 'arweave', symbol: 'AR', name: 'Arweave' },
  { id: 'basic-attention-token', symbol: 'BAT', name: 'Basic Attention Token' },
  { id: '0x', symbol: 'ZRX', name: '0x' },
  { id: 'enjincoin', symbol: 'ENJ', name: 'Enjin Coin' },
  { id: 'gala', symbol: 'GALA', name: 'Gala' },
  { id: 'illuvium', symbol: 'ILV', name: 'Illuvium' },
  { id: 'immutable-x', symbol: 'IMX', name: 'Immutable X' },
  { id: 'loopring', symbol: 'LRC', name: 'Loopring' },
  { id: 'mina-protocol', symbol: 'MINA', name: 'Mina Protocol' },
  { id: 'oasis-network', symbol: 'ROSE', name: 'Oasis Network' },
  { id: 'secret', symbol: 'SCRT', name: 'Secret' },
  { id: 'waves', symbol: 'WAVES', name: 'Waves' },
  { id: 'zilliqa', symbol: 'ZIL', name: 'Zilliqa' }
];

export const fiatCurrencies = [
  { code: 'USD', name: 'US Dollar' },
  { code: 'EUR', name: 'Euro' },
  { code: 'GBP', name: 'British Pound' },
  { code: 'JPY', name: 'Japanese Yen' },
  { code: 'AUD', name: 'Australian Dollar' },
  { code: 'CAD', name: 'Canadian Dollar' },
  { code: 'CHF', name: 'Swiss Franc' },
  { code: 'CNY', name: 'Chinese Yuan' },
  { code: 'INR', name: 'Indian Rupee' },
  { code: 'BRL', name: 'Brazilian Real' },
  { code: 'RUB', name: 'Russian Ruble' },
  { code: 'KRW', name: 'South Korean Won' },
  { code: 'MXN', name: 'Mexican Peso' },
  { code: 'SGD', name: 'Singapore Dollar' },
  { code: 'NZD', name: 'New Zealand Dollar' },
  { code: 'ZAR', name: 'South African Rand' },
  { code: 'SEK', name: 'Swedish Krona' },
  { code: 'NOK', name: 'Norwegian Krone' },
  { code: 'DKK', name: 'Danish Krone' },
  { code: 'PLN', name: 'Polish Złoty' },
  { code: 'HKD', name: 'Hong Kong Dollar' },
  { code: 'TRY', name: 'Turkish Lira' },
  { code: 'IDR', name: 'Indonesian Rupiah' },
  { code: 'THB', name: 'Thai Baht' },
  { code: 'AED', name: 'UAE Dirham' },
  { code: 'SAR', name: 'Saudi Riyal' },
  { code: 'ILS', name: 'Israeli New Shekel' },
  { code: 'PHP', name: 'Philippine Peso' },
  { code: 'MYR', name: 'Malaysian Ringgit' },
  { code: 'CZK', name: 'Czech Koruna' },
  { code: 'HUF', name: 'Hungarian Forint' },
  { code: 'RON', name: 'Romanian Leu' },
  { code: 'HRK', name: 'Croatian Kuna' },
  { code: 'BGN', name: 'Bulgarian Lev' },
  { code: 'ISK', name: 'Icelandic Króna' },
  { code: 'UAH', name: 'Ukrainian Hryvnia' },
  { code: 'CLP', name: 'Chilean Peso' },
  { code: 'COP', name: 'Colombian Peso' },
  { code: 'PEN', name: 'Peruvian Sol' },
  { code: 'ARS', name: 'Argentine Peso' },
  { code: 'VND', name: 'Vietnamese Dong' },
  { code: 'NGN', name: 'Nigerian Naira' },
  { code: 'EGP', name: 'Egyptian Pound' },
  { code: 'PKR', name: 'Pakistani Rupee' },
  { code: 'BDT', name: 'Bangladeshi Taka' },
  { code: 'KES', name: 'Kenyan Shilling' },
  { code: 'GHS', name: 'Ghanaian Cedi' },
  { code: 'DZD', name: 'Algerian Dinar' },
  { code: 'MAD', name: 'Moroccan Dirham' },
  { code: 'TWD', name: 'New Taiwan Dollar' }
]; 